### ISSUE TITLE
[speech-to-text] recognize() method without sessions failing with JsonParseException

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#308]
The following Java program (renamed for attachment) tests the recognize() method without sessions: 
[STTrecognizeSessionless.txt](https://github.com/watson-developer-cloud/java-sdk/files/291916/STTrecognizeSessionless.txt).  I can't find anything wrong in the call to the method, though I could be mistaken.  But the program produces a JsonParseException, presumably on the options object that is passed to the call.:

```
Exception in thread "main" com.google.gson.JsonParseException: Expecting array but found object: {}
        at com.google.gson.JsonArrayDeserializationVisitor.startVisitingObject(JsonArrayDeserializationVisitor.java:89)
        at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:119)
        at com.google.gson.JsonDeserializationContextDefault.fromJsonArray(JsonDeserializationContextDefault.java:67)
        at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:52)
        at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:663)
        at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:624)
        at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
        at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
        at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
        at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
        at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
        at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
        at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
        at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:663)
        at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:624)
        at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
        at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
        at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
        at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
        at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
        at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
        at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
        at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:663)
        at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:624)
        at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
        at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
        at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
        at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
        at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
        at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
        at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
        at com.google.gson.Gson.fromJson(Gson.java:551)
        at com.google.gson.Gson.fromJson(Gson.java:498)
       at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:105)
        at com.ibm.watson.developer_cloud.service.WatsonService.executeRequest(WatsonService.java:184)
        at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.recognize(SpeechToText.java:285)
        at com.ibm.watson.developer_cloud.speech_to_text.v1.STTrecognizeSessionless.main(STTrecognizeSessionless.java:19)
```

I can pass along the audio file if you need it.

Testing with **java-sdk-2.10.0-jar-with-dependencies.jar**.

**Comment by jeffpk62** [comment]
Additional note:  Not surprisingly, I get the same error when calling recognize() with sessions, and I get the error when passing either a sessionId string or a SpeechSession object with the request.

**Comment by max-vogler** [comment]
Seems like to be a v2 problem - testing a similar code with v3 works.
```java
SpeechToText service = new SpeechToText();
service.setUsernameAndPassword("...", "...");
RecognizeOptions options = new RecognizeOptions.Builder().contentType("audio/flac").timestamps(true).wordAlternativesThreshold(0.9).build();
SpeechResults results = service.recognize(new File("test.flac"), options).execute();
    
System.out.print(results);
```

**Comment by jeffpk62** [comment]
Thanks, Max.  I'm going to need to try working with the v3.0 jar file to see what happens there.  Sadly, time is not my friend at the moment.

**Comment by germanattanasio** [comment]
@jeffpk62 I'm closing this since it's fixed in `v.3.0.0`.

**Comment by robinsonbonilha** [comment]
This problem didnt fix in v3.0.1, because I had same problem when I use builder.timestamps(true)

**Comment by germanattanasio** [comment]
@robinsonbonilha can you share the code you are using and the version of the sdk. We have a test case that checks this error...

**Comment by robinsonbonilha** [comment]
Thank you German, I use jdk 7, follows:
```
    public static void main(String[] args) {
		SpeechToText service = new SpeechToText();
		service.setUsernameAndPassword("user", "pass");
		
		Builder builder = new RecognizeOptions.Builder();
		builder.interimResults(true);
		builder.contentType(HttpMediaType.AUDIO_WAV);
		builder.model("pt-BR_BroadbandModel");	
		builder.timestamps(true);
		RecognizeOptions options = builder.build();	
		File audio = new File("C:\\TESTE_AUDIO.wav");
		SpeechResults transcript = service.recognize(audio, options).execute();
		String traducao = null;
		for(Transcript tsc : transcript.getResults()){
			for(SpeechAlternative alt : tsc.getAlternatives()){
				for(SpeechTimestamp time : alt.getTimestamps()){
					System.out.println("ini:"+time.getStartTime() + ", fim:"+time.getEndTime()+", texto:"+time.getWord());
				}
				traducao = alt.getTranscript();				
			}
		}
		System.out.println(traducao);
	}
```

**Comment by germanattanasio** [comment]
@max-vogler can you take a look at this?

**Comment by max-vogler** [comment]
I just tested your code @robinsonbonilha. It works for me on JDK7 with `3.0.0-RC1`, `3.0.1` and `3.0.2-SNAPSHOT`. Are you using 3.0.1? Could you please upload your stack trace and audio file, so I can reproduce this?

**Comment by robinsonbonilha** [comment]
Hi, I use java-sdk-3.0.1-jar-with-dependencies.jar, follows stack trace:

```
Exception in thread "main" com.google.gson.JsonParseException: Expecting array but found object: {}
	at com.google.gson.JsonArrayDeserializationVisitor.startVisitingObject(JsonArrayDeserializationVisitor.java:89)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:119)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonArray(JsonDeserializationContextDefault.java:67)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:52)
	at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:663)
	at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:624)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
	at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
	at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:663)
	at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:624)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
	at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
	at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:663)
	at com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter.deserialize(DefaultTypeAdapters.java:624)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
	at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:551)
	at com.google.gson.Gson.fromJson(Gson.java:498)
	at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:90)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:73)
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:396)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:179)
	at br.com.lume.common.util.SpeechToTextExample.main(SpeechToTextExample.java:33)
```

**Comment by robinsonbonilha** [comment]
When I updated the gson.jar of my project, show a new stack trace, follows:
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 7 column 20`

**Comment by max-vogler** [comment]
@robinsonbonilha, I still cannot reproduce the error. I set up a testing repository [max-vogler/speech-to-text-issue-308](https://github.com/max-vogler/speech-to-text-issue-308). It would be great if you could:

1. Check out the repository under [max-vogler/speech-to-text-issue-308](https://github.com/max-vogler/speech-to-text-issue-308) and run it on your local machine, to see if you get the error because of your JDK or audio file

2. If the error persists, open a pull request to upload your audio file to my repository

**Comment by robinsonbonilha** [comment]
Hi @max-vogler, Same error with your audio. When I created a new project without GSON lib, the problem resolved with both audios.
I think that the problem is related with my version of gson-2.3.jar in my current project is different from the version used in sdk v3.0.1 lib for parse JSON objects.

**Comment by robinsonbonilha** [comment]
I resolve the problem removing my gson lib that my project, and now my project use the same gson lib existing in jdk watson, but I recommend that you in next version update the gson library of your sdk or change the name class

**Comment by max-vogler** [comment]
@robinsonbonilha: Good to see that it worked out for you! Thanks for the heads up. The Watson Java SDK uses the more recent Gson 2.6.2 already though.

**Comment by robinsonbonilha** [comment]
Thank you @max-vogler
